-- Rollback: 011_app_market_engine
DROP TABLE IF EXISTS subscriptions CASCADE;
DROP TABLE IF EXISTS entitlements CASCADE;
DROP TABLE IF EXISTS channels CASCADE;
DROP TABLE IF EXISTS releases CASCADE;
DROP TABLE IF EXISTS artifacts CASCADE;
DROP TABLE IF EXISTS packages CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS publishers CASCADE;
