apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubernetes-provider.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubernetes-provider.labels" . | nindent 4 }}
{{- if .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
{{- end }}
automountServiceAccountToken: true