apiVersion: v1
kind: Service
metadata:
  name: {{ include "rbac-syncer.fullname" . }}
  labels: {{ include "rbac-syncer.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
    - name: health
      port: {{ .Values.service.healthPort }}
      targetPort: health
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "rbac-syncer.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
