apiVersion: v1
kind: Secret
metadata:
  name: hnb-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  tunnel-token-secret: {{ .Values.global.tunnelTokenSecret | default "change-me-tunnel-secret" | quote }}
