replicaCount: 1
image:
  repository: hnb/{{ .Chart.Name }}
  tag: ""
  pullPolicy: ""
nats:
  url: ""
  existingClientTLSSecret: ""
db:
  dsn: ""
runtimeProviders: ""
serviceTokenSecret: ""
resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
